### ISSUE TITLE
CLI doesn't load Config file.

### ISSUE THREAD

**Issue by ddaza** [brigade/scss-lint#621] opened 2015-10-21 19:32 UTC
I have a `.scss-lint.yml` in my  `project` directory.

`project > assets > stylesheets`

If I run the cli from the `project` directory. like so  `scss-lint assets/style/_awesome.scss` the config file is loaded. 

But, if I am inside the folder `stylesheets` the cli does not traverse back to the root and ignores my configs.

This is a problem because main editor is vim (with syntastic) and it changes the current folder depending of the file that is being edited. This will ignore the custom configs.

Other linters work this way (jslint, eslint). Perhaps we can traverse back to the first appearance of a `.git` directory since that usually is the root.

**Comment by sds** [comment] 2015-10-29 07:09
Duplicate of #516.

FWIW, `vim` doesn't change the working directory based on the file you are editing&mdash;it uses the directory you were in when you first opened vim (unless you or some plugin you use changed it). I use `scss-lint` with Syntastic and I've never experienced this problem, but I'm always working from the root directory of the repository, which is where my `.scss-lint.yml` is located.

**Closed by sds** 2015-10-29 07:09 UTC
Labels: duplicate

**Comment by ddaza** [comment] 2015-10-29 14:43
vim does change the file directory if you have `set autochdir` flag on. I use this to have folder structure auto-complete localized to each file. This is extremely useful when you're deep in the folder structure and wanna update mixins/styles from some other file.

**Comment by sds** [comment] 2015-10-29 15:47
Ah, TIL about `autochdir`. Thanks for sharing!
