### ISSUE TITLE
Space after variable colon

### ISSUE THREAD

**Issue by drwaky** [brigade/scss-lint#680] opened 2016-01-18 19:13 UTC
There is any way to make the same behavior of SpaceAfterPropertyColon but for Variables?
(A Space after colon)
Ex:
**Good**
  *$h1-size:  24px;*

**Bad**
  *$h1-size:24px;*

**Comment by cih** [comment] 2016-01-18 20:32
Hey @drwaky,

There is an issue open for this one https://github.com/brigade/scss-lint/issues/445, I did implement the `SpaceAfterVariableName` part and planned on getting round to implementing the `SpaceAfterPropertyColon` too, dropped the ball on that one. I'll take a look at this and get a PR up soon!

**Comment by drwaky** [comment] 2016-01-19 13:58
hi @cih,
Thanks for answer me so soon :) I'll be looking for your implementation.

**Comment by sds** [comment] 2016-01-19 19:46
Duplicate of #445.

**Closed by sds** 2016-01-19 19:46 UTC
Labels: duplicate
