### ISSUE TITLE
CSS Comb autocorrector?

### ISSUE THREAD

**Issue by connorshea** [brigade/scss-lint#745] opened 2016-03-02 22:58 UTC
I'm not sure if scss-lint has feature parity with [CSS Comb](https://github.com/csscomb/csscomb.js), but would it be possible to make a generator for a CSS Comb config from a SCSS Lint config? This would provide a sort of autocorrect functionality, and would be quite useful.

**Comment by sds** [comment] 2016-03-03 08:36
Unless I'm missing something, CSS Comb operates on CSS, not SCSS.

The two languages have significant differences. An SCSS parser can parse CSS, but not vice versa.

A quick look at their documentation doesn't mention anything about SCSS. Thus I don't think it makes any sense for SCSS-Lint to support generating a config for this tool. 

Again, let me know if I'm missing something.

**Comment by connorshea** [comment] 2016-03-05 23:20
@sds the developers have fixed [a few](https://github.com/csscomb/csscomb.js/issues/172) [SCSS-related](https://github.com/csscomb/csscomb.js/issues/376) [bugs](https://github.com/csscomb/csscomb.js/issues/319), so it supports SCSS just fine as far as I can tell.

**Comment by sds** [comment] 2016-03-06 01:39
Ah, thanks for clarifying, @connorshea. You would think that would be mentioned in their docs somewhere!

I've no doubt that some would find such a tool useful, but I have reservations about including it directly in the SCSS-Lint project.

To me, this makes more sense as a separate tool. You have two projects whose available configuration options are changing over time–it's not great for either project (referring to SCSS-Lint/CSSComb) to have to "watch" the other project for changes. It's good to be wary of integrating with other tools, as it's hard to anticipate or catch regressions, since you have two different entities managing each project. 

However, a separate project by someone who uses both tools extensively (and thus understands their configurations well) would be ideal as a maintainer for such a project.

If someone wanted to tackle the task of figuring out a (sensible, which may or may not be entirely possible) mapping of SCSS configuration to CSSComb configuration and ensure that mapping stays up-to-date, I'd be happy to link to the tool in our documentation.

Thank you for suggesting ways we can improve SCSS-Lint! I'm going to close this, but I'm open to hearing other thoughts.

**Closed by sds** 2016-03-06 01:39 UTC
Labels: enhancement, question

**Comment by connorshea** [comment] 2016-03-06 17:09
That's understandable, thanks for the consideration :)
