### ISSUE TITLE
VariableForProperty warning thrown for Sass functions

### ISSUE THREAD

**Issue by RRorg** [brigade/scss-lint#882] opened 2017-01-14 23:27 UTC
`color: mycolorfunction(mycolorparameter);` will throw a `VariableForProperty` warning, although mycolorfunction is not a literal value.

**Comment by trotzig** [comment] 2017-01-16 09:45
I believe this is a duplicate of #794. Closing, let me know if you disagree!

**Closed by trotzig** 2017-01-16 09:45 UTC
