### ISSUE TITLE
grid-template-columns: [ name ] throws a syntax error 

### ISSUE THREAD

**Issue by ciar4n** [brigade/scss-lint#906] opened 2017-06-19 12:58 UTC
A name in square brackets appears to throw a syntax error..

`grid-template-columns: [linename] 100px;`

https://developer.mozilla.org/en/docs/Web/CSS/grid-template-columns

**Comment by sds** [comment] 2017-08-05 20:04
Hey @ciar4n,

This is actually a [bug with the Sass parser](https://github.com/sass/sass/issues/1963) that SCSS-lint uses, which has been fixed in Sass 3.5. 

Unfortunately SCSS-Lint does not yet support Sass 3.5. There is an open issue to track adding support [here](https://github.com/brigade/scss-lint/issues/877). Closing this as a duplicate of that issue. 

Thanks for the report!

**Closed by sds** 2017-08-05 20:04 UTC
Labels: duplicate
