### ISSUE TITLE
Option to exclude pseudo-classes from nesting count

### ISSUE THREAD

**Issue by viveleroi** [brigade/scss-lint#477] opened 2015-06-02 16:48 UTC
Pseudo-classes appear to be included in the nesting count. I'm sure some users may need this, but I'd like the ability to disable them. In my view, the nesting depth is intended to limit individual elements specified in the selector chain (each one increases specificity). Pseudo-classes and pseudo-elements are typically never used without a qualifying element, so I don't believe they should count as a fully separate level.

    .panel {
        > header {
            .btn-clear {
                &:hover { }
            }
        }
    }

**Comment by sds** [comment] 2015-06-04 16:37
Hey @viveleroi,

This request sounds reasonable. The one gotcha is that while it may not be common, you _can_ have a comma sequence that contains more than just pseudo classes, e.g.

```
.panel {
    > header {
        .btn-clear {
            &:hover,
            .some-class { } // <-- Now increasing nesting depth is necessary
        }
    }
}
```

Thus any implementation will need to handle this case.

A pull request would be most welcome!

**Comment by viveleroi** [comment] 2015-06-04 17:46
I would PR it but will have trouble finding the time, and am not up to speed on ruby ;p

**Comment by sds** [comment] 2015-06-08 02:32
I'm realizing that this is a duplicate of #384, so closing in favor of that issue.

**Closed by sds** 2015-06-08 02:32 UTC
Labels: duplicate
