### ISSUE TITLE
NestingDepth raised unexpected error linting file

### ISSUE THREAD

**Issue by ste-m** [brigade/scss-lint#589] opened 2015-09-08 13:44 UTC
SublimeLinter: scss: _tmpl-pricing.scss ['/Users/ftc/.rvm/bin/rvm-auto-ruby', '-S', 'scss-lint', '--config', '/Users/ftc/.scss-lint.yml'] 
	SublimeLinter: scss output:
	SCSSLint::Linter::NestingDepth raised unexpected error linting file /var/folders/yd/r9bztf0n19d4v88hcy0j532c0000gn/T/SublimeLinter3-ftc/_tmpl-pricing.scss: 'undefined method `members' for nil:NilClass'
	/Users/ftc/.rvm/gems/ruby-2.1.2/gems/scss_lint-0.40.1/lib/scss_lint/linter/nesting_depth.rb:40:in `simple_selectors'
	/Users/ftc/.rvm/gems/ruby-2.1.2/gems/scss_lint-0.40.1/lib/scss_lint/linter/nesting_depth.rb:34:in `ignore_selectors?'
	/Users/ftc/.rvm/gems/ruby-2.1.2/gems/scss_lint-0.40.1/lib/scss_lint/linter/nesting_depth.rb:15:in `visit_rule'
	/Users/ftc/.rvm/gems/ruby-2.1.2/gems/sass-3.4.13/lib/sass/tree/visitors/base.rb:36:in `visit'
	/Users/ftc/.rvm/gems/ruby-2.1.2/gems/scss_lint-0.40.1/lib/scss_lint/linter.rb:131:in `visit'
	/Users/ftc/.rvm/gems/ruby-2.1.2/gems/scss_lint-0.40.1/lib/scss_lint/linter.rb:142:in `block in visit_children'
	/Users/ftc/.rvm/gems/ruby-2.1.2/gems/scss_lint-0.40.1/lib/scss_lint/linter.rb:140:in `each'
	/Users/ftc/.rvm/gems/ruby-2.1.2/gems/scss_lint-0.40.1/lib/scss_lint/linter.rb:140:in `visit_children'
	/Users/ftc/.rvm/gems/ruby-2.1.2/gems/sass-3.4.13/lib/sass/tree/visitors/base.rb:38:in `visit'
	/Users/ftc/.rvm/gems/ruby-2.1.2/gems/scss_lint-0.40.1/lib/scss_lint/linter.rb:131:in `visit'
	/Users/ftc/.rvm/gems/ruby-2.1.2/gems/scss_lint-0.40.1/lib/scss_lint/linter.rb:142:in `block in visit_children'
	/Users/ftc/.rvm/gems/ruby-2.1.2/gems/scss_lint-0.40.1/lib/scss_lint/linter.rb:140:in `each'
	/Users/ftc/.rvm/gems/ruby-2.1.2/gems/scss_lint-0.40.1/lib/scss_lint/linter.rb:140:in `visit_children'
	/Users/ftc/.rvm/gems/ruby-2.1.2/gems/sass-3.4.13/lib/sass/tree/visitors/base.rb:36:in `block in visit'
	/Users/ftc/.rvm/gems/ruby-2.1.2/gems/scss_lint-0.40.1/lib/scss_lint/linter/nesting_depth.rb:11:in `visit_root'
	/Users/ftc/.rvm/gems/ruby-2.1.2/gems/sass-3.4.13/lib/sass/tree/visitors/base.rb:36:in `visit'
	/Users/ftc/.rvm/gems/ruby-2.1.2/gems/scss_lint-0.40.1/lib/scss_lint/linter.rb:131:in `visit'
	/Users/ftc/.rvm/gems/ruby-2.1.2/gems/scss_lint-0.40.1/lib/scss_lint/linter.rb:25:in `run'
	/Users/ftc/.rvm/gems/ruby-2.1.2/gems/scss_lint-0.40.1/lib/scss_lint/runner.rb:48:in `run_linter'
	/Users/ftc/.rvm/gems/ruby-2.1.2/gems/scss_lint-0.40.1/lib/scss_lint/runner.rb:29:in `block in find_lints'
	/Users/ftc/.rvm/gems/ruby-2.1.2/gems/scss_lint-0.40.1/lib/scss_lint/runner.rb:27:in `each'
	/Users/ftc/.rvm/gems/ruby-2.1.2/gems/scss_lint-0.40.1/lib/scss_lint/runner.rb:27:in `find_lints'
	/Users/ftc/.rvm/gems/ruby-2.1.2/gems/scss_lint-0.40.1/lib/scss_lint/runner.rb:17:in `block in run'
	/Users/ftc/.rvm/gems/ruby-2.1.2/gems/scss_lint-0.40.1/lib/scss_lint/runner.rb:16:in `each'
	/Users/ftc/.rvm/gems/ruby-2.1.2/gems/scss_lint-0.40.1/lib/scss_lint/runner.rb:16:in `run'
	/Users/ftc/.rvm/gems/ruby-2.1.2/gems/scss_lint-0.40.1/lib/scss_lint/cli.rb:58:in `scan_for_lints'
	/Users/ftc/.rvm/gems/ruby-2.1.2/gems/scss_lint-0.40.1/lib/scss_lint/cli.rb:51:in `act_on_options'
	/Users/ftc/.rvm/gems/ruby-2.1.2/gems/scss_lint-0.40.1/lib/scss_lint/cli.rb:28:in `run'
	/Users/ftc/.rvm/gems/ruby-2.1.2/gems/scss_lint-0.40.1/bin/scss-lint:6:in `<top (required)>'
	/Users/ftc/.rvm/gems/ruby-2.1.2/bin/scss-lint:23:in `load'
	/Users/ftc/.rvm/gems/ruby-2.1.2/bin/scss-lint:23:in `<main>'
	Report this bug at https://github.com/brigade/scss-lint/issues

	To help fix this issue, please include:
	- The above stack trace
	- SCSS-Lint version: 0.40.1
	- Sass version: 3.4.13
	- Ruby version: 2.1.2
	- Contents of .scss-lint.yml 

And here are is the content of Contents of .scss-lint.yml 

	# Default application configuration that all configurations inherit from.

	scss_files: "**/*.scss"
	plugin_directories: ['.scss-linters']

	# List of gem names to load custom linters from (make sure they are already
	# installed)
	plugin_gems: []

	linters:
	  BangFormat:
	    enabled: true
	    space_before_bang: true
	    space_after_bang: false

	  BemDepth:
	    enabled: false
	    max_elements: 1

	  BorderZero:
	    enabled: true
	    convention: zero # or `none`

	  ColorKeyword:
	    enabled: true

	  ColorVariable:
	    enabled: true

	  Comment:
	    enabled: true

	  DebugStatement:
	    enabled: true

	  DeclarationOrder:
	    enabled: true

	  DisableLinterReason:
	    enabled: false

	  DuplicateProperty:
	    enabled: true

	  ElsePlacement:
	    enabled: true
	    style: same_line # or 'new_line'

	  EmptyLineBetweenBlocks:
	    enabled: true
	    ignore_single_line_blocks: true

	  EmptyRule:
	    enabled: true

	  ExtendDirective:
	    enabled: false

	  FinalNewline:
	    enabled: true
	    present: true

	  HexLength:
	    enabled: true
	    style: short # or 'long'

	  HexNotation:
	    enabled: true
	    style: lowercase # or 'uppercase'

	  HexValidation:
	    enabled: true

	  # id selectors are not good, but to reference forms they are still the best choiche.
	  IdSelector:
	    enabled: false

	  ImportantRule:
	    enabled: true

	  ImportPath:
	    enabled: true
	    leading_underscore: false
	    filename_extension: false

	  Indentation:
	    enabled: true
	    allow_non_nested_indentation: false
	    character: space # or 'tab'
	    width: 2

	  LeadingZero:
	    enabled: true
	    style: exclude_zero # or 'include_zero'

	  MergeableSelector:
	    enabled: true
	    force_nesting: true

	  NameFormat:
	    enabled: true
	    allow_leading_underscore: true
	    convention: hyphenated_lowercase # or 'camel_case', or 'snake_case', or a regex pattern

	  NestingDepth:
	    enabled: true
	    max_depth: 4
	    ignore_parent_selectors: true

	  PlaceholderInExtend:
	    enabled: true

	  PropertyCount:
	    enabled: false
	    include_nested: false
	    max_properties: 10

	  PropertySortOrder:
	    enabled: true
	    ignore_unspecified: false
	    min_properties: 2
	    separate_groups: false

	  PropertySpelling:
	    enabled: true
	    extra_properties: []

	  PropertyUnits:
	    enabled: true
	    global: [
	      'ch', 'em', 'ex', 'rem',                 # Font-relative lengths
	      'cm', 'in', 'mm', 'pc', 'pt', 'px', 'q', # Absolute lengths
	      'vh', 'vw', 'vmin', 'vmax',              # Viewport-percentage lengths
	      'deg', 'grad', 'rad', 'turn',            # Angle
	      'ms', 's',                               # Duration
	      'Hz', 'kHz',                             # Frequency
	      'dpi', 'dpcm', 'dppx',                   # Resolution
	      '%']                                     # Other
	    properties: {}

	  QualifyingElement:
	    enabled: true
	    allow_element_with_attribute: true
	    allow_element_with_class: true
	    allow_element_with_id: false

	  SelectorDepth:
	    enabled: true
	    max_depth: 4

	  SelectorFormat:
	    enabled: true
	    convention: hyphenated_lowercase # or 'strict_BEM', or 'hyphenated_BEM', or 'snake_case', or 'camel_case', or a regex pattern

	  Shorthand:
	    enabled: true
	    allowed_shorthands: [1, 2, 3]

	  SingleLinePerProperty:
	    enabled: true
	    allow_single_line_rule_sets: true

	  # false: imagine a case like the BS h1 h2 h3 h4 ...
	  SingleLinePerSelector:
	    enabled: false

	  SpaceAfterComma:
	    enabled: true

	  SpaceAfterPropertyColon:
	    enabled: true
	    style: one_space # or 'no_space', or 'at_least_one_space', or 'aligned'

	  SpaceAfterPropertyName:
	    enabled: true

	  SpaceAfterVariableName:
	    enabled: true

	  SpaceAroundOperator:
	    enabled: true
	    style: one_space # or 'no_space'

	  SpaceBeforeBrace:
	    enabled: true
	    style: space # or 'new_line'
	    allow_single_line_padding: false

	  SpaceBetweenParens:
	    enabled: true
	    spaces: 0

	  StringQuotes:
	    enabled: true
	    style: single_quotes # or double_quotes

	  TrailingSemicolon:
	    enabled: true

	  TrailingWhitespace:
	    enabled: true

	  TrailingZero:
	    enabled: false

	  UnnecessaryMantissa:
	    enabled: true

	  UnnecessaryParentReference:
	    enabled: true

	  UrlFormat:
	    enabled: true

	  UrlQuotes:
	    enabled: true

	  VariableForProperty:
	    enabled: false
	    properties: []

	  VendorPrefix:
	    enabled: true
	    identifier_list: base
	    additional_identifiers: []
	    excluded_identifiers: []

	  ZeroUnit:
	    enabled: true

	  Compass::*:
	    enabled: false

**Comment by sds** [comment] 2015-09-08 16:10
Hey @ste-m,

This bug should be fixed in the latest version of `scss-lint` (0.41.0 at time of writing). Please upgrade and let us know if you're still seeing the issue.

Duplicate of #541.

**Closed by sds** 2015-09-08 16:10 UTC
Labels: duplicate

**Comment by ste-m** [comment] 2015-09-09 07:20
@sds sorry for that, didn't find the duplicate, works well. Thanx!
